spring:
  application:
    name: revhire
  
  datasource:
    url: jdbc:mysql://localhost:3306/revhire_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Vivekg123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

file:
  upload-dir: uploads/resumes

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.revhire.revhire: DEBUG
    org.springframework.security: DEBUG
